---
- name: install packages for building ruby
  become: yes
  yum: name={{ item }} state=present
  with_items:
    - readline-devel
    - zlib-devel
    - libyaml-devel
    - libffi-devel
    - openssl-devel
    - libxml2-devel
    - libxslt-devel
    - cmake
...
